# Nord, dark mode (see fuzzel.ini)

[main]
icon-theme=Nordzy-Launcher-Dark

[colors]
# RRGGBBAA; the background is slightly see-through, blurred by Hyprland
background=2e3440f2
text=d8dee9ff
message=d8dee9ff
prompt=88c0d0ff
placeholder=4c566aff
input=eceff4ff
match=88c0d0ff
selection=3b4252ff
selection-text=eceff4ff
selection-match=8fbcbbff
counter=4c566aff
border=88c0d0ff
